import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import './globals.css'
import type { Metadata } from 'next'
import { PrimeReactProvider } from "primereact/api";
import Header from "./components/Header";


export const metadata: Metadata = {
  title: 'PrimeReact',
  description: 'Generated by create next app + PrimeReact',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const value = {};

  return (
    <PrimeReactProvider value={value}>
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <Header />
          {children}
        </body>
      </html>
    </PrimeReactProvider>
  )
}
